import Layout from '@containers/Layout';
import MainConatiner from '@containers/MainContainer';
import AppContext from '@context/AppContext';
import Head from 'next/head';
import { useContext } from 'react';

export default function Home() {
  const { state } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {state.viewConsultarRutas && <MainConatiner element={state.viewConsultarRutas} />}
      </Layout>
    </>
  );
}
