import Layout from '@containers/Layout';
import MainConatiner from '@containers/MainContainer';
import Header from '@components/Header';
import NavOptions from '@components/NavOptions';

import AppContext from '@context/AppContext';
import Head from 'next/head';
import { useContext } from 'react';

export default function Home() {
  const { state } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NavOptions />
      <Layout>
        {state.viewConsultarRutas.stateView && <MainConatiner currentView={state.viewConsultarRutas} />}
        {state.viewConsultarPedidos.stateView && <MainConatiner currentView={state.viewConsultarPedidos} />}
        {state.viewConsultarClientes.stateView && <MainConatiner currentView={state.viewConsultarClientes} />}
      </Layout>
    </>
  );
}
